### ISSUE TITLE
Update CosmWasm std dependency version to 1.2.x？

### ISSUE THREAD

**Issue by lshoo** [sei-protocol/sei-cosmwasm#61]
Hi，
The cosmwasm-std latest version is 1.2.6， are you going to update the dependency to this？
I noticed the sei-cosmwam latest release version before four months ago.

Thanks！

**Comment by lshoo** [comment]
After I updated the sei-cosmwasm dependencies to latest, `cargo test` is ok

**Comment by Kbhat1** [comment]
The version of cosmwasm-std used is 1.1. There are some incompatibilities with 1.2.6 but we are planning to upgrade to later versions of cosmwasm-std soon.

**Comment by Kbhat1** [comment]
There hasn't been any updates on this issue. If there are still issues here / concerns, please just re open another issue. Closing this.
