### ISSUE TITLE
What is the contract adderss `sei14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sh9m79m` mean?

### ISSUE THREAD

**Issue by lshoo** [sei-protocol/sei-cosmwasm#65]
Hi guys,
I found this address [`sei14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sh9m79m`](https://github.com/sei-protocol/sei-cosmwasm/blob/main/contracts/sei-tester/src/contract.rs#L100C29-L100C91) and [`sei14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sh9m79m`](https://github.com/sei-protocol/sei-cosmwasm/blob/main/contracts/sei-tester/deployment/deployment_script.sh#L29C73-L29C136) in sei-cosmwasm code base， what about this address？
Can i change it?

**Comment by Kbhat1** [comment]
This is just for test purposes in the `sei-tester` contract. This shouldn't be hard coded, but it just represents the contract address on a local chain (as that is the contract address of the first initialized contract on a chain). This will be updated soon, but this does not affect the sei-cosmwasm package.
