### ISSUE TITLE
Handle `PlaceOrders` reply rsponse error

### ISSUE THREAD

**Issue by lshoo** [sei-protocol/sei-cosmwasm#67]
Hi guys,

I copy codes of `handle_place_order_reply` function from `sei-tester`, but it can't work in my project.
I got an error in my [handle reply code](https://github.com/orderbook-labs/seadex/blob/main/contracts/pool/src/contract/reply.rs#L33):
```
Error parsing into type MsgPlaceOrdersResponse: failed to parse data)
```
I saw the `sei dex module` handle reply is not as same as `cosmwasm-std`，may i take a mistake or miss something?
how to fix it?
thanks

**Comment by lshoo** [comment]
I found integration-tests in `sei-tester` with Cosmos::Custom` instead of `SeiMsg::PlaceOrders`, also don't use `PlaceOrders`  in ExecuteMsg in `sei-tester`。

I'm curious why ExecuteMsg::PlaceOrders wasn't used directly. Can someone explain?

**Comment by Kbhat1** [comment]
Hi Ishoo, are you still seeing this issue. Sei-cosmwasm was updated recently. What version of `cosmwasm-std` are you using? We use `cosmwasm-std` version 1.1 and haven't tested with later versions

**Comment by Kbhat1** [comment]
There hasn't been any updates on this issue. If there are still issues here / concerns, please just re open another issue. Closing this.
